-- CREATE TABLE clients(
-- 	id SERIAL PRIMARY KEY NOT NULL,
--     nome VARCHAR(100) NOT NULL,
--     documento VARCHAR(14) NOT NULL,
--     tipo VARCHAR(15) NOT NULL,
--     email VARCHAR(100) NOT NULL,
--     telefone VARCHAR(14)    
-- );

-- CREATE TABLE accounts(
-- 	id SERIAL PRIMARY KEY NOT NULL,
--     numero VARCHAR(5) NOT NULL,
--     agencia VARCHAR(4) NOT NULL,
--     saldo INT NOT NULL,
--     cliente_id INT  NOT NULL,
--     FOREIGN KEY(cliente_id) REFERENCES clients(id)
-- );

-- CREATE TABLE operations(
-- 	id SERIAL NOT NULL PRIMARY KEY,
--     conta_origem INT NOT NULL,
--     conta_destino INT,
--     valor INT NOT NULL,
--     taxa INT NOT NULL,
--     tipo VARCHAR(15) NOT NULL,
--     FOREIGN KEY (conta_origem) REFERENCES accounts(id),
--     FOREIGN KEY (conta_destino) REFERENCES accounts(id)
-- );